// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxSQfH-Ze2hv7skgm8FPHUTfKGQSVId9o',
    appId: '1:112296499639:web:92c0b01891da9e7b49f032',
    messagingSenderId: '112296499639',
    projectId: 'kooked-28d4c',
    authDomain: 'kooked-28d4c.firebaseapp.com',
    storageBucket: 'kooked-28d4c.firebasestorage.app',
    measurementId: 'G-6FHRXZTB4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlbGPedl5HttkMihbCm8mTF3lXq5mF7So',
    appId: '1:112296499639:android:a2109b5cd05dea3049f032',
    messagingSenderId: '112296499639',
    projectId: 'kooked-28d4c',
    storageBucket: 'kooked-28d4c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvR3rBuyt-rquj9kGzvCdKRXT0QJYD114',
    appId: '1:112296499639:ios:836b143314889dad49f032',
    messagingSenderId: '112296499639',
    projectId: 'kooked-28d4c',
    storageBucket: 'kooked-28d4c.firebasestorage.app',
    iosClientId: '112296499639-9mkbhd79n4s53q2r231q07ma6rj990lh.apps.googleusercontent.com',
    iosBundleId: 'com.kooked.kooked',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvR3rBuyt-rquj9kGzvCdKRXT0QJYD114',
    appId: '1:112296499639:ios:836b143314889dad49f032',
    messagingSenderId: '112296499639',
    projectId: 'kooked-28d4c',
    storageBucket: 'kooked-28d4c.firebasestorage.app',
    iosClientId: '112296499639-9mkbhd79n4s53q2r231q07ma6rj990lh.apps.googleusercontent.com',
    iosBundleId: 'com.kooked.kooked',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxSQfH-Ze2hv7skgm8FPHUTfKGQSVId9o',
    appId: '1:112296499639:web:4f94b5e9e7c05de549f032',
    messagingSenderId: '112296499639',
    projectId: 'kooked-28d4c',
    authDomain: 'kooked-28d4c.firebaseapp.com',
    storageBucket: 'kooked-28d4c.firebasestorage.app',
    measurementId: 'G-8TRNTPJ1PW',
  );
}
